[package]
name = "Junto-Alpha-API"
version = "0.1.0"
authors = ["jdeepee <joshuadparkin@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = { version = "1.0", features = ["ssl"] }
dotenv = "0.10.0"
